<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0-windows</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Connect.Core/Connect.Core.csproj" />
    <Compile Include="../../src/Connect.App/PrivateSettings.cs" Link="PrivateSettings.cs" />
  </ItemGroup>
</Project>
